//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiQA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAAttachmentComment
    {
        public int Id { get; set; }
        public int AttachmentId { get; set; }
        public int CommentId { get; set; }
    
        public virtual QAComment QAComment { get; set; }
        public virtual QAAttachment QAAttachment { get; set; }
    }
}
