//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiQA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewQAFollowingUp
    {
        public int id { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> ReferrerId { get; set; }
        public string ReferrerName { get; set; }
        public Nullable<int> ReferredId { get; set; }
        public string ReferredName { get; set; }
        public Nullable<bool> Confirmation { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateReferr { get; set; }
        public Nullable<System.DateTime> DateConfirmation { get; set; }
    }
}
