//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiQA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewQAByEmployeeCount
    {
        public int type { get; set; }
        public string TypeTitle { get; set; }
        public int EmployeeId { get; set; }
        public int NotDeterminedCount { get; set; }
        public int ConfirmedCount { get; set; }
        public int ReferredCount { get; set; }
    }
}
