//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiQA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewQADashDispatch
    {
        public Nullable<int> type { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public Nullable<int> YearMonth { get; set; }
        public Nullable<int> CatagoryId { get; set; }
        public string CategoryTitle { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
