//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiQA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewQaDashGround
    {
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> YearMonth { get; set; }
        public Nullable<int> DamageById { get; set; }
        public string DamageByTitle { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
