//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiQA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewQADispatch
    {
        public Nullable<int> Id { get; set; }
        public int FlightId { get; set; }
        public string FlightNumber { get; set; }
        public string Register { get; set; }
        public string Route { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> DateReport { get; set; }
        public Nullable<System.DateTime> DateSign { get; set; }
        public Nullable<System.DateTime> DateOccurrence { get; set; }
        public Nullable<System.DateTime> OPTimeReceived { get; set; }
        public string OPReportedBy { get; set; }
        public string OPLocation { get; set; }
        public Nullable<int> CatagoryId { get; set; }
        public string EmployeeName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> OPCancelled { get; set; }
        public Nullable<System.DateTime> OPCancelledTime { get; set; }
        public Nullable<bool> OPACChanged { get; set; }
        public Nullable<System.DateTime> OPACChangedTime { get; set; }
        public Nullable<bool> OPCrewChanged { get; set; }
        public Nullable<System.DateTime> OPCrewChangedTime { get; set; }
        public Nullable<bool> OPFlightPerformed { get; set; }
        public Nullable<System.DateTime> OPFlightPerformedTime { get; set; }
        public string CatagoryTitle { get; set; }
        public string OPSummary { get; set; }
        public string DISLocation { get; set; }
        public Nullable<int> DISTimeDuration { get; set; }
        public string DISActionResult { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> dateStatus { get; set; }
        public Nullable<int> StatusEmployeeId { get; set; }
        public string StatusEmployeeName { get; set; }
        public string Result { get; set; }
    }
}
