//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FDM()
        {
            this.FDMEventActions = new HashSet<FDMEventAction>();
        }
    
        public int Id { get; set; }
        public string Severity { get; set; }
        public string EventName { get; set; }
        public string Value { get; set; }
        public Nullable<double> Minor { get; set; }
        public Nullable<double> Major { get; set; }
        public Nullable<double> Critical { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<System.DateTime> TDDatetime { get; set; }
        public string P1 { get; set; }
        public string P2 { get; set; }
        public string Phase { get; set; }
        public string StateName { get; set; }
        public string Context { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> TODatetime { get; set; }
        public string Units { get; set; }
        public string ValueName { get; set; }
        public Nullable<int> FlightId { get; set; }
        public string PFLR { get; set; }
        public string Limit { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FileName { get; set; }
        public Nullable<int> P1Id { get; set; }
        public Nullable<int> P2Id { get; set; }
        public Nullable<int> RegisterId { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public string IP { get; set; }
        public Nullable<int> IPId { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public string Key { get; set; }
        public string AircraftType { get; set; }
        public Nullable<int> AircraftTypeId { get; set; }
        public Nullable<bool> Removed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDMEventAction> FDMEventActions { get; set; }
    }
}
