//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDMEventAction
    {
        public int Id { get; set; }
        public Nullable<int> FDMId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> PreActionId { get; set; }
        public Nullable<int> CrewId { get; set; }
        public string UserId { get; set; }
        public string ActionInfo { get; set; }
        public Nullable<int> FDPId { get; set; }
        public string ClassId { get; set; }
        public string TrainingResult { get; set; }
        public string ActionType { get; set; }
        public Nullable<System.DateTime> DateTrainingAction { get; set; }
        public Nullable<System.DateTime> DateTrainingVisit { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CourseDuration { get; set; }
        public Nullable<System.DateTime> DateCourseStart { get; set; }
        public Nullable<System.DateTime> DateCourseEnd { get; set; }
        public string CourseInstructor { get; set; }
        public string CourseLocation { get; set; }
    
        public virtual FDM FDM { get; set; }
        public virtual FDP FDP { get; set; }
    }
}
