//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CrewSecretCode> CrewSecretCodes { get; set; }
        public virtual DbSet<FlightInformation> FlightInformations { get; set; }
        public virtual DbSet<Ac_MSN> Ac_MSN { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<ViewLegTime> ViewLegTimes { get; set; }
        public virtual DbSet<AppLeg> AppLegs { get; set; }
        public virtual DbSet<FDMCptAnnually> FDMCptAnnuallies { get; set; }
        public virtual DbSet<FDMCptEventDaily> FDMCptEventDailies { get; set; }
        public virtual DbSet<FDMEventDaily> FDMEventDailies { get; set; }
        public virtual DbSet<FDMFoEventMonthly> FDMFoEventMonthlies { get; set; }
        public virtual DbSet<FDMPhaseMonthly> FDMPhaseMonthlies { get; set; }
        public virtual DbSet<FDMRegCptMonthly> FDMRegCptMonthlies { get; set; }
        public virtual DbSet<FDMRegFoMonthly> FDMRegFoMonthlies { get; set; }
        public virtual DbSet<ViewFDM> ViewFDMs { get; set; }
        public virtual DbSet<FDMCptEventMonthly> FDMCptEventMonthlies { get; set; }
        public virtual DbSet<FDMRegDaily> FDMRegDailies { get; set; }
        public virtual DbSet<FDMRegEventMonthly1> FDMRegEventMonthly1 { get; set; }
        public virtual DbSet<FDM> FDMs { get; set; }
        public virtual DbSet<FDMAVG> FDMAVGs { get; set; }
        public virtual DbSet<FDMCptAll> FDMCptAlls { get; set; }
        public virtual DbSet<FDMCptMonthly> FDMCptMonthlies { get; set; }
        public virtual DbSet<FDMCptFoMonthly> FDMCptFoMonthlies { get; set; }
        public virtual DbSet<FDMCptIpMonthly> FDMCptIpMonthlies { get; set; }
        public virtual DbSet<FDMFoMonthly> FDMFoMonthlies { get; set; }
        public virtual DbSet<FDMCptAirportEventMonthly> FDMCptAirportEventMonthlies { get; set; }
        public virtual DbSet<FDMCptAirportMonthly> FDMCptAirportMonthlies { get; set; }
        public virtual DbSet<FDMAirportMonthly> FDMAirportMonthlies { get; set; }
        public virtual DbSet<FDMRegMonthly> FDMRegMonthlies { get; set; }
        public virtual DbSet<FDMMonthly> FDMMonthlies { get; set; }
    }
}
