//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFDM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFDMEventAction
    {
        public int Id { get; set; }
        public Nullable<int> FDMId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> PreActionId { get; set; }
        public Nullable<int> CrewId { get; set; }
        public string UserId { get; set; }
        public string ActionInfo { get; set; }
        public Nullable<int> FDPId { get; set; }
        public string ClassId { get; set; }
        public string TrainingResult { get; set; }
        public string ActionType { get; set; }
        public Nullable<System.DateTime> DateTrainingAction { get; set; }
        public Nullable<System.DateTime> DateTrainingVisit { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CourseDuration { get; set; }
        public Nullable<System.DateTime> DateCourseStart { get; set; }
        public Nullable<System.DateTime> DateCourseEnd { get; set; }
        public string CourseInstructor { get; set; }
        public string CourseLocation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JobGroup { get; set; }
        public string Context { get; set; }
        public Nullable<double> Critical { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Duration { get; set; }
        public string EventName { get; set; }
        public Nullable<int> FlightId { get; set; }
        public string Limit { get; set; }
        public Nullable<double> Major { get; set; }
        public Nullable<double> Minor { get; set; }
        public string PFLR { get; set; }
        public string Severity { get; set; }
        public string Phase { get; set; }
        public string StateName { get; set; }
        public Nullable<System.DateTime> TDDatetime { get; set; }
        public Nullable<System.DateTime> TODatetime { get; set; }
        public string Type { get; set; }
        public string Units { get; set; }
        public string Value { get; set; }
        public string ValueName { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public string ToAirportIATA { get; set; }
        public string FromAirportIATA { get; set; }
        public string Register { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public string FlightNumber { get; set; }
    }
}
