//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiReportFlight.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ppa_Entities : DbContext
    {
        public ppa_Entities()
            : base("name=ppa_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RptFuelOFP> RptFuelOFPs { get; set; }
        public virtual DbSet<ViewLegCrew> ViewLegCrews { get; set; }
        public virtual DbSet<RptFlightRVSM> RptFlightRVSMs { get; set; }
        public virtual DbSet<ViewFormB> ViewFormBs { get; set; }
        public virtual DbSet<ViewFormC> ViewFormCs { get; set; }
        public virtual DbSet<XFlightCrew> XFlightCrews { get; set; }
        public virtual DbSet<ViewFinMonthlyRoute> ViewFinMonthlyRoutes { get; set; }
        public virtual DbSet<ViewFlightDaily> ViewFlightDailies { get; set; }
    }
}
